[colors.bright]
black = "#5c6370"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#FFFFFF"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#FFFFFF"
yellow = "#d79921"

[colors.primary]
background = "#282828"
foreground = "#FFFFFF"

[font]
size = 12

[font.normal]
family = "JetBrainsMonoNerdFont"
style = "Regular"
