[colors.primary]
background = '#141311'
foreground = '#e7e2dd'

[colors.cursor]
text = '#141311'
cursor = '#e7e2dd'

[colors.vi_mode_cursor]
text = '#141311'
cursor = '#fff7e7'

[colors.search.matches]
foreground = '#4b463c'
background = '#eefddb'

[colors.search.focused_match]
foreground = '#4b463c'
background = '#fff7e7'

[colors.footer_bar]
foreground = '#4b463c'
background = '#e7e2dd'

[colors.hints.start]
foreground = '#4b463c'
background = '#cec6b3'

[colors.hints.end]
foreground = '#4b463c'
background = '#cec6b3'

[colors.selection]
text = '#cdc6b8'
background = '#4b463c'


[colors.normal]
black   = '#4b463c'
red     = '#ffb4ab'
green   = '#fff7e7'
yellow  = '#cec6b3'
blue    = '#eefddb'
magenta = '#d4c69f'
cyan    = '#cec6b3'
white   = '#e7e2dd'


[colors.bright]
black   = '#969084'
red     = '#ffb4ab'
green   = '#fff7e7'
yellow  = '#cec6b3'
blue    = '#eefddb'
magenta = '#d4c69f'
cyan    = '#cec6b3'
white   = '#e7e2dd'


[colors.dim]
black   = '#4b463c'
red     = '#ffb4ab'
green   = '#fff7e7'
yellow  = '#cec6b3'
blue    = '#eefddb'
magenta = '#d4c69f'
cyan    = '#cec6b3'
white   = '#e7e2dd'
